version: "2"

linters:
  enable:
    - wsl_v5
  settings:
    errcheck:
      exclude-functions:
        - "(github.com/ras0q/rsss/internal/database.DB).Close"
        - "(*github.com/google/generative-ai-go/genai.Client).Close"
      verbose: true
